#!/usr/bin/env bash

## Run project's Terminus
##
## Usage: fin terminus [aruments]
##
##

if [ -z $TERMINUS_TOKEN ]; then
  echo "TERMINUS_TOKEN must be present in the docksal.env"
  exit 1
fi

if [ $1 = 'login' ]; then
  fin exec terminus auth:login --machine-token=$TERMINUS_TOKEN
else
  fin exec terminus "$@"
fi
